### ISSUE TITLE
observation_space

### ISSUE THREAD

**Issue by Lwz0613** [Unnon97/VisualRL_Grasper#1]
hey,I just started to learn rl,can you tell me how to provide the observation space while running the script? thanks bro

**Comment by Unnon97** [comment]
Hello, for this project, you need to provide the observation space with reference to what the camera sees. This is given in this format. I am also still experimenting, however this worked for initial setup run.
Put this part in the init function of the environment script(GraspingEnv.py) file in gym_grasper folder:
`def __init__(...... , ..... , observation_space = Space):
self.observation_space = spaces.Box(
            low=0,
            high=255,
            shape=(3, self.IMAGE_WIDTH, self.IMAGE_HEIGHT),
            dtype=np.uint8
        )
`

Hope it helps.

**Comment by Lwz0613** [comment]
> 您好，这个项目需要您提供观察空间，参考摄像头所见。这是以这种格式给出的。我还在试验，但这适用于初始设置运行。 将此部分放在 gym_grasper 文件夹中环境脚本（GraspingEnv.py）文件的初始化函数中： `def __init__(...... , ..... , observation_space = Space): self.observation_space = spaces.Box( low=0, high=255, shape=(3, self.IMAGE_WIDTH, self.IMAGE_HEIGHT), dtype=np.uint8 ) `
> 
> 希望能帮助到你。

Hey bro, sorry to bother you, may I ask that mujocoenv's __init__ lacks a variable（Space）? I tried your method but it doesn't work, thank you

**Comment by Unnon97** [comment]
Hey, ya that can be solved by adding ´from gym.spaces import Space' in the import lines.
